### ISSUE TITLE
NullReferenceException thrown when invoking TextMeasurer.MeasureBounds

### ISSUE THREAD

**Issue by AndrewShepherd** [SixLabors/Fonts#276] opened 2022-06-06 00:24 UTC
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Fonts
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The method `TextMeasurer.MeasureBounds` throws a `System.NullReferenceException` when using the [OpenSans](https://fonts.google.com/specimen/Open+Sans) font.

### Steps to Reproduce
I downloaded the OpenSans font from [Google Fonts](https://fonts.google.com/specimen/Open+Sans)

The following code demonstrates the issue:

```
using SixLabors.Fonts;

var fontCollection = new FontCollection();
FontFamily fontFamily = fontCollection.Add("./OpenSans/OpenSans-Regular.ttf");
Font font = new Font(fontFamily, 100, FontStyle.Regular);
var rendererOptions = new TextOptions(font)
{
	HorizontalAlignment = HorizontalAlignment.Left,
	VerticalAlignment = VerticalAlignment.Top,
};
FontRectangle bounds = TextMeasurer.MeasureBounds(
	"Hello World",
	rendererOptions
);
```

The call to `MeasureBounds` throws a `NullReference` exception. Here are the exception details:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SixLabors.Fonts
  StackTrace:
   at SixLabors.Fonts.Tables.AdvancedTypographic.GPosTable.GetFeatureLookups(Tag& stageFeature, ScriptClass script)
   at SixLabors.Fonts.Tables.AdvancedTypographic.GPosTable.TryUpdatePositions(FontMetrics fontMetrics, GlyphPositioningCollection collection, KerningMode kerningMode, Boolean& kerned)
   at SixLabors.Fonts.StreamFontMetrics.UpdatePositions(GlyphPositioningCollection collection, KerningMode kerningMode)
   at SixLabors.Fonts.FileFontMetrics.UpdatePositions(GlyphPositioningCollection collection, KerningMode kerningMode)
   at SixLabors.Fonts.TextLayout.ProcessText(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextLayout.GenerateLayout(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextMeasurer.TextMeasurerInt.MeasureBounds(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextMeasurer.MeasureBounds(String text, TextOptions options)
   at Program.<Main>$(String[] args) in C:\Development\PlayArea\ImageSharp\MeasureBounds\MeasureBounds\Program.cs:line 11

```

### System Configuration

- Fonts version: 1.0.0-beta 16 (I am not explicitly including it)
- Other Six Labors packages and versions:
   - SixLabors.ImageSharp version 2.1.2
   - SixLabors.ImageSharp.Drawing version 1.0.0-beta14
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 6.0

**Comment by JimBobSquarePants** [comment] 2022-06-06 00:27
Thanks for all the info. 

Looks like a duplicate of  https://github.com/SixLabors/Fonts/issues/266 if you specifically target 1.0.0-beta17 the issue should be resolved.

**Comment by AndrewShepherd** [comment] 2022-06-06 00:39
I have attempted to explicitly target 1.0.0-beta17, but the problem still occurs.

To confirm if I've done it correctly: here are the references in my .csproj file:

```
	<ItemGroup>
		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.2" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />
		<PackageReference Include="SixLabors.Fonts" Version="1.0.0-beta17" />
	</ItemGroup>
```

And here are the properties of the .DLL file in my project output folder:

![fonts-dll-properties](https://user-images.githubusercontent.com/2449034/172077350-2bbfadde-a157-40bd-9ce6-570f7114eca0.png)

**Comment by James-Jackson-South** [comment] 2022-06-06 00:42
Looks like you're including it properly. Can you please add the specific font from the family to the PR so I can have a look?

**Comment by AndrewShepherd** [comment] 2022-06-06 00:46
Here is the file OpenSans-Regular.ttf that my example code was loading loading:

[OpenSans-Regular.zip](https://github.com/SixLabors/Fonts/files/8841136/OpenSans-Regular.zip)

**Comment by JimBobSquarePants** [comment] 2022-06-06 00:47
Great. I'll have a look asap.

**Comment by loraderon** [comment] 2022-06-10 11:11
I do think #266 is a duplicate since it was reported against 1.0.0-beta17. 

The fix hasn't been released to nuget yet, I haven't tested the myget **beta17.8** (https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.Fonts) but it would probably work since the fix was "obvious" 😄

**Comment by JimBobSquarePants** [comment] 2022-06-10 11:25
Ha! I thought it was against 16!

Yeah, the MyGet version should work though I’ll double check.

**Comment by AndrewShepherd** [comment] 2022-06-12 23:22
I have tested this code using the myget repository, version 1.0.0-beta17.8. I can confirm it now runs without crashing.

```
	<ItemGroup>
		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.2" />
		<PackageReference Include="SixLabors.Fonts" Version="1.0.0-beta17.8" />
	</ItemGroup>
```

Even though it was triggered through a different call then in #266, it's clearly the same error.

Not sure whether this case should be closed now or if it should be left open until the fix is in the public repository, just to avoid more duplicate posts. I'll leave that to you to decide.

**Comment by JimBobSquarePants** [comment] 2022-06-14 07:27
Let's close this one. The search should still pick up duplicates.

**Closed by JimBobSquarePants** 2022-06-14 07:27 UTC
Labels: needs triage
